"""Add user_selections to EventPlan

Revision ID: 0014e5d6a59e
Revises: 86aa9facb686
Create Date: 2026-04-09 20:28:58.009447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0014e5d6a59e'
down_revision = '86aa9facb686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_selections', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_plans', schema=None) as batch_op:
        batch_op.drop_column('user_selections')

    # ### end Alembic commands ###
